#!/bin/sh

set -e
# set -x

# Setup config files, read config variables.

WORKINGDIR=$(pwd)
CONFIGNAME=".boilerplate"
CONFIGDIR="${WORKINGDIR}/${CONFIGNAME}"
CONFIG="${CONFIGDIR}/config.sh"
CREATE="${CONFIGDIR}/create.sh"

BPBRANCH="boilerplate"
BPMESSAGE="update boilerplate"
BPPRECOMMIT="prek"
if [ -f "${CONFIG}" ]; then
    . "${CONFIG}"
fi

# Implement undo, which resets the boilerplate branch to its parent.

if [ "X$1" = "X-u" ]; then
    git branch -f "${BPBRANCH}" "${BPBRANCH}^"

    exit
fi

# Implement init, which creates a git repo with an empty root commit.

if [ "X$1" = "X-i" ]; then
    git init

    if [ -n "$2" ]; then
        git persona -n "$2"
    fi

    git commit --allow-empty -m "init: empty root commit"

    mkdir -p "${CONFIGDIR}"
    touch "${CREATE}"
    cat > "${CONFIG}" <<EOF
BPBRANCH="${BPBRANCH}"
BPMESSAGE="${BPMESSAGE}"

# prek, pre-commit or the empty string
# Skipping the hook on the boilerplate branch may be useful if the template
# hook requires the package to be installed, e.g. in order to run tests.
BPPRECOMMIT="${BPPRECOMMIT}"
EOF

    exit
fi

# Implement boilerplate update. Join all arguments into the commit message.

if [ -n "$*" ]; then
    BPMESSAGE="$*"
fi

GITEMAIL="$(git config --local user.email)"
GITNAME="$(git config --local user.name)"

if [ -z $(git branch --list "${BPBRANCH}") ]; then
    git branch "${BPBRANCH}"
fi

PROJECTBASE=$(mktemp -d)
git clone --shared --no-checkout --branch "${BPBRANCH}" . "${PROJECTBASE}"
echo "Working inside ${PROJECTBASE}"

CLONE="${PROJECTBASE}/bp"
mkdir "${CLONE}"
cd "${CLONE}"

export CONFIGDIR
cp -a "${CONFIGDIR}" .

sh "${CREATE}"

rm -rf "${CLONE}/.git"
mv "${PROJECTBASE}/.git" "${CLONE}/"

git add .

if [ -n "$BPPRECOMMIT" -a -n "$(which ${BPPRECOMMIT})" ]; then
    "$BPPRECOMMIT" install --allow-missing-config
fi

if [ -n "${GITEMAIL}" ]; then git config --local user.email "${GITEMAIL}"; fi
if [ -n "${GITNAME}" ]; then git config --local user.name "${GITNAME}"; fi

git commit -m "${BPMESSAGE}"
git push

rm -rf .git

cd "${WORKINGDIR}"

rm -r "${CLONE}"
rmdir "${PROJECTBASE}"
echo "Removed ${PROJECTBASE}"
